name: summarizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - pip
  - pip:
      - typer==0.15.1
      - openai==1.61.1
      - ollama==0.4.7
      - moviepy==2.1.2
      - gradio==5.15.0
      - ctranslate2==4.4.0
      - faster-whisper==1.1.1
      - setuptools >= 6
